### PR TITLE
code cleanup

### PR DESCRIPTION
**Pull request by mambax7**

### CODE REVIEW

**Comment by mambax7** [comment]
up? 
Any comments, feedback on these changes?

**Comment by informatux45** [comment]
Hi Michael,
How are you?I worked yesterday on liaise and i don't merge your request :-( ... Sorry!Is it only cleanup code?
INFORMATUX Patricehttp://www.informatux.com/

Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : "Mamba (Michael Beck)" notifications@github.com 
Date : 03/12/2015  00:13  (GMT+01:00) 
À : informatux45/liaise liaise@noreply.github.com 
Objet : Re: [liaise] code cleanup (#1) 

up?

**Comment by mambax7** [comment]
Code cleanup, bug fixes, adding missing translations, etc. 
You should look into the files to see the changes.

**Comment by informatux45** [comment]
Hello Michael,

I saw the code cleanup but can you tell me what kind of bug have you fixed
cause the module have been tested on the net and there is no problem.
I added the missing translations yesterday and added constants in code.
Thanks

Patrice

**Review by informatux45 — APPROVED** [review]

**Review by informatux45 — APPROVED** [review]

**Review by informatux45 — APPROVED** [review]

**Pull request closed without merging**
